export const products = [
    {
        title: "Amo Cafezinho",
        price: "149,90",
        description: "",
        items: "Cesta MDF reutilizável • Suco de Uva • Pão de mel • Cookies • Mini folhados recheados • Bolo de cenoura com gotas e cobertura de chocolate • Iogurte Grego • Granola • Frutas da estação • Drip Coffee • Sachês de chá • Cappuccino em pó • Café com leite em pó • Biscoitos amanteigados caseiros • Vaso de flor",
        images: {
            1: "img/amoCafezinho/1.jpg",
            2: "img/amoCafezinho/2.jpg",
            3: "img/amoCafezinho/3.jpg",
            4: "img/amoCafezinho/4.jpg",
        },
    },
    {
        title: "Amo Frutas",
        price: "150,90",
        description: "",
        items: "Cesta MDF reutilizável • Suco integral de uva ou laranja • Bolo de cenoura com gotas e cobertura de chocolate • Frutas da estação • Mini folhados recheados • Mini torradinhas temperadas • Biscoitos amanteigados caseiros • Geleia • Torrada Tradicional • Vaso de Flor • Polenguinho",
        images: {
            1: "img/amoFrutas/1.jpg",
            2: "img/amoFrutas/2.jpg",
            3: "img/amoFrutas/3.jpg",
        },
    },
    {
        title: "Amo Bombons",
        price: "129,90",
        description: "",
        items: "Cesta MDF reutilizável • Vaso de flor • Bolo de cenoura com gotas e cobertura de chocolate • Suco integral de uva e de laranja • Biscoitos amanteigados caseiros • Bombons • Mini torradinhas temperadas • Mini folhados recheados",
        images: {
            1: "img/amoBombons/1.jpg",
            2: "img/amoBombons/2.jpg",
            3: "img/amoBombons/3.jpg",
            4: "img/amoBombons/4.jpg",
            5: "img/amoBombons/5.jpg",
            6: "img/amoBombons/6.jpg",
            7: "img/amoBombons/7.jpg",
            8: "img/amoBombons/8.jpg",
        },
    },
    {
        title: "Amo Estar Com Você",
        price: "179,90",
        description: "",
        items: "Vaso de Flor • Cesta MDF reutilizável • Garrafa Cappuccino Pronto • Biscoitos amanteigados caseiros • Bolo de cenoura com gotas e cobertura de chocolate • Mel • Polenguinho • Bombons • Salada de frutas • Granola • Torrada tradicional • Garrafas de iogurte • Croissants",
        images: {
            1: "img/amoEstar/1.jpg",
            2: "img/amoEstar/2.jpg",
            3: "img/amoEstar/3.jpg",
        },
    },
    {
        title: "Amo Afeto",
        price: "139,90",
        description: "",
        items: "Caixa em mdf reutilizável • Suco de frutas • Café Drip Coffee • Frios - queijo e peito de Peru • Queijo processado Polenguinho • Pao - Mini baquete • Torradas • Brownie recheado • Cookies com gotas de chocolate • Bolo de cenoura com ganache • Frutas da estação",
        images: {
            1: "img/amoAfeto/1.jpg",
            2: "img/amoAfeto/2.jpg",
            3: "img/amoAfeto/3.jpg",
            4: "img/amoAfeto/4.jpg",
        },
    },
    {
        title: "Amo Leveza",
        price: "150,90",
        description: "",
        items: "Cesta MDF reutilizável • Vaso de flor • Suco de laranja natural • Bolo de banana sem açúcar • Frutas da estação  • Mini folhados recheados • Cesta MDF reutilizável • Vaso de flor • Suco de laranja natural • Bolo de banana sem açúcar • Frutas da estação  • Mini folhados recheados",
        images: {
            1: "img/amoLeveza/1.jpg",
            2: "img/amoLeveza/2.jpg",
            3: "img/amoLeveza/3.jpg",
            4: "img/amoLeveza/4.jpg",
            5: "img/amoLeveza/5.jpg",
            6: "img/amoLeveza/6.jpg",
            7: "img/amoLeveza/7.jpg",
            8: "img/amoLeveza/8.jpg",
        },
    },
    {
        title: "Amo Celebrar",
        price: "150,90",
        description: "",
        items: "Bolo afetivo • Pão de mel • Suco de Fruta • Drip coffee • Frutas da estação • Crossaints • Pães de batata recheados • Peito de peru • Queijo • Creme de ricota • Damasco • Mix de nuts • Iogurte natural com granola  (ramikim de louça) • Pães de queijo",
        images: {
            1: "img/amoCelebrar/1.jpg",
            2: "img/amoCelebrar/2.jpg",
            3: "img/amoCelebrar/3.jpg",
            4: "img/amoCelebrar/4.jpg",
            5: "img/amoCelebrar/5.jpg",
            6: "img/amoCelebrar/6.jpg",
            7: "img/amoCelebrar/7.jpg",
            8: "img/amoCelebrar/8.jpg",
            9: "img/amoCelebrar/9.jpg",
            10: "img/amoCelebrar/10.jpg",
            11: "img/amoCelebrar/11.jpg",
            12: "img/amoCelebrar/12.jpg",
            13: "img/amoCelebrar/13.jpg",
            14: "img/amoCelebrar/14.jpg",
            15: "img/amoCelebrar/15.jpg",
            16: "img/amoCelebrar/16.jpg",
            17: "img/amoCelebrar/17.jpg",
            18: "img/amoCelebrar/18.jpg",
            19: "img/amoCelebrar/19.jpg",
            20: "img/amoCelebrar/20.jpg",
            21: "img/amoCelebrar/21.jpg",
            22: "img/amoCelebrar/22.jpg",
            23: "img/amoCelebrar/23.jpg",
            24: "img/amoCelebrar/24.jpg",
            25: "img/amoCelebrar/25.jpg",
            26: "img/amoCelebrar/26.jpg",
            27: "img/amoCelebrar/27.jpg",
            28: "img/amoCelebrar/28.jpg",
            29: "img/amoCelebrar/29.jpg",
            30: "img/amoCelebrar/30.jpg",
        },
    },
    {
        title: "Amo Queijos",
        price: "150,90",
        description: "",
        items: "Caixa de MDF • Frutas da estação • Waffle • Mini folhados recheados • Mussarela com damasco • Mix de nuts • Amendoins • Salaminho • Mussarela • Queijo Gouda • Creme de Ricota • Provolone Desidratado • Bombons • Heineken",
        images: {
            1: "img/amoQueijos/1.jpg",
            2: "img/amoQueijos/2.jpg",
            3: "img/amoQueijos/3.jpg",
            4: "img/amoQueijos/4.jpg",
            5: "img/amoQueijos/5.jpg",
            6: "img/amoQueijos/6.jpg",
            7: "img/amoQueijos/7.jpg",
            8: "img/amoQueijos/8.jpg",
            9: "img/amoQueijos/9.jpg",
            10: "img/amoQueijos/10.jpg",
            11: "img/amoQueijos/11.jpg",
            12: "img/amoQueijos/12.jpg",
            13: "img/amoQueijos/13.jpg",
            14: "img/amoQueijos/14.jpg",
            15: "img/amoQueijos/15.jpg",
            16: "img/amoQueijos/16.jpg",
            17: "img/amoQueijos/17.jpg",
            18: "img/amoQueijos/18.jpg",
        },
    },
    {
        title: "Amo Petiscos",
        price: "150,90",
        description: "",
        items: "Cesta MDF reutilizável • Cerveja Heineken • Batata Pringles • Salamitos Snack Sadia  • Azeitonas • Salgadinho Torcida • Mini Torradinhas Temperadas • Bombons • Amendoins crocantes saborizados • Mix de nuts • Espetinho de presunto e queijo",
        images: {
            1: "img/amoPetiscos/1.jpg",
            2: "img/amoPetiscos/2.jpg",
            3: "img/amoPetiscos/3.jpg",
            4: "img/amoPetiscos/4.jpg",
            5: "img/amoPetiscos/5.jpg",
            6: "img/amoPetiscos/6.jpg",
            7: "img/amoPetiscos/7.jpg",
            8: "img/amoPetiscos/8.jpg",
            9: "img/amoPetiscos/9.jpg",
            10: "img/amoPetiscos/10.jpg",
        },
    },
    {
        title: "Simples Amor",
        price: "179,90",
        description: "",
        items: "Cesta MDF reutilizável • Drip Coffee • Chocolate • Cappuccino em pó • Polenguinho • Brownie recheado • Nutella • Suco integral de uva ou laranja • Frutas da estação • Pão francês com parmesão • Biscoito palmier de canela • Biscoitos amanteigados caseiros • Mini folhados recheados",
        images: {
            1: "img/simplesAmor/1.jpg",
            2: "img/simplesAmor/2.jpg",
            3: "img/simplesAmor/3.jpg",
            4: "img/simplesAmor/4.jpg",
            5: "img/simplesAmor/5.jpg",
            6: "img/simplesAmor/6.jpg",
            7: "img/simplesAmor/7.jpg",
            8: "img/simplesAmor/8.jpg",
            9: "img/simplesAmor/9.jpg",
            10: "img/simplesAmor/10.jpg",
        },
    },
    {
        title: "Amor a 2",
        price: "150,90",
        description: "",
        items: "Caixote reutilizável • 2 Suco de laranja • Broinhas de fubá • Bolo de cenoura com ganache • Bolo de banana sem açúcar • Croissants recheados • Biscuit sensação com cobertura de chocolate ao leite • Diversas frutas da estação",
        images: {
            1: "img/amorA2/1.jpg",
            2: "img/amorA2/2.jpg",
            3: "img/amorA2/3.jpg",
            4: "img/amorA2/4.jpg",
            5: "img/amorA2/5.jpg",
            6: "img/amorA2/6.jpg",
        },
    },
    {
        title: "Bela Infância",
        price: "150,90",
        description: "",
        items: "Cesta MDF reutilizável • Pão de batata com presunto e queijo • Toddynho • Mini folhados recheados • Bolo de cenoura com cobertura de chocolate • Danoninho Ice • Kinder Ovo • Cata-vento com balinha • Chiclete • Copo com balas Fini • Pirulito colorido",
        images: {
            1: "img/belaInfancia/1.jpg",
            2: "img/belaInfancia/2.jpg",
        },
    },
    {
        title: "Amo Momentos",
        price: "150,90",
        description: "",
        items: "Caixote reutilizável • Suco de frutas • 2 Cafes - Drip coffee • Amanteigados • Croissants recheados • Torradas temperadas • Broinhas de fubá • Frutas da estação • 2 Bolo de cenoura com cobertura de ganache • Mini Flor",
        images: {
            1: "img/val/1.jpg",
            2: "img/val/2.jpg",
            3: "img/val/3.jpg",
        },
    },
    {
        title: "Naked Cake",
        price: "29,90",
        description: "",
        items: "MDF • Suco",
        images: {
            1: "img/bolinho/1.jpg",
            2: "img/bolinho/2.jpg",
        },
    },
];
